export enum StarCitizenKey {
  COMMLINK = 'default.toggle_contact',
  MOBIGLAS = 'spaceship_hud.mobiglas',
  STARMAP = 'spaceship_hud.v_starmap',
  DECOUPLE = 'spaceship_movement.v_ifcs_toggle_vector_decoupling',
  GSAFE = 'spaceship_movement.v_ifcs_toggle_gforce_safety',
  AFTER_BURNER = 'spaceship_movement.v_afterburner',
  MAX_THRUST = '',
  ESP = 'spaceship_movement.v_ifcs_toggle_esp',
  SCM_LIMITER = '',
  FREE_LOOK = 'spaceship_view.v_view_freelook_mode',
  SPOOL_DRIVE = 'spaceship_movement.v_toggle_qdrive_spooling',
  QUANTUM_JUMP = 'spaceship_movement.v_toggle_qdrive_engagement',
  SELF_DESTRUCT = 'spaceship_general.v_self_destruct',
  EJECT = 'spaceship_general.v_eject',
  LOCK = 'spaceship_general.v_doors_lock_all',
  UNLOCK = 'spaceship_general.v_doors_unlock_all',
  SCANNING = 'spaceship_targeting.v_toggle_scan_mode',
  LIGHTS = 'lights_controller.v_lights',
  OPEN_DOORS = 'spaceship_general.v_doors_open_all',
  CLOSE_DOORS = 'spaceship_general.v_doors_close_all',
  FLIGHT_READY = 'spaceship_general.v_flightready',
  LANDING_GEAR = 'spaceship_movement.v_toggle_landing_system',
  AUTOLAND = 'spaceship_movement.v_autoland',
  CYCLE_CAMERA = 'spaceship_view.v_view_cycle_fwd',
  EXIT_SEAT = 'spaceship_general.v_exit',
}
